  <div class="menu" style="margin-bottom: -5em; margin-left: -1em; margin-top: 6.5em; padding-top: 1em; padding-left: 1em; padding-bottom: 0.5em; position:relative; top: -6em;">
    <div id="nav" style="padding-bottom: 0.5em;">
      <a id="back" style="width: 7em; margin-left: 1em; text-decoration:none;" href="javascript:history.go(-1)"><img src="img/buuf_back.png" style="height: 16px; width: auto; vertical-align:middle; margin-right:8px;"><font style="color: orange; font-size: 1em; font-weight: bold;">Go back</font></a>
    </div>
  </div>
