  <h1>PiNG <font style="color: orange;">Projects</font></h1>

  <form style="position:relative; top: -3.2em; text-align: right;">
    <input type="text" style="position:relative; width: 15em;" value="">
    <input type="button" style="width: auto;" value="Search" onclick="location.href='search.php'">
  </form>

  <div class="menu" style="margin-left: -1em; margin-top: 1.5em; padding-top: 1em; padding-left: 1em; padding-bottom: 0.5em; position:relative; top: -3em;">
      <ul id="nav">
        <li id="home"><a href="index.php">Home</a></li>
	<li id="list"><a href="list.php">View as list</a></li>
	<li id="new"><a href="create.php">New project</a></li>
      </ul>
  </div>
