  <h1><a href="index.php">PiNG <font style="color: orange;">Projects</font></a></h1>
  <div style="width: 25%; margin-left: 75%; position:relative; top: -3.2em; text-align: right;">
  <form id="search" method="get" action="search.php">
    <input name="q" size=22 /><input style="margin-left: 0.4em;" type=submit value="Search"/>
  </form>
  </div>

  <div class="menu" style="margin-left: -1em; margin-top: 1.5em; padding-top: 1em; padding-left: 1em; padding-bottom: 0.5em; position:relative; top: -3em;">
      <ul id="nav">
        <li id="home"><a href="index.php">Home</a></li>
	<li id="list"><a href="list.php">View as list</a></li>
	<li id="new"><a href="create.php">New project</a></li>
      </ul>
  </div>
